---
permalink: concept-requirement-for-using-fileshares-in-windows.html 
sidebar: sidebar 
keywords: netApp smis-s provider, fileshare, ntfs-only volume 
summary: 'Quando si utilizzano le condivisioni file (CIFS share) su Windows, il volume su cui viene creata la fileshare deve essere un volume solo NTFS.' 
---
= Requisito per l'utilizzo di file eshare su Windows
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Quando si utilizzano le condivisioni file (CIFS share) su Windows, il volume su cui viene creata la fileshare deve essere un volume solo NTFS.

Se si desidera creare una fileshare e utilizzarla su Windows, il volume in cui viene creata la fileshare deve essere un volume solo NTFS. In questo modo si evitano problemi con le credenziali che accedono alla fileshare.

Da System Center 2016 Virtual Machine Manager (SCVMM), è possibile creare macchine virtuali (VM) solo su fileshare creati su volumi solo NTFS. I volumi misti e UNIX non sono supportati.



== Creazione di un volume da utilizzare per le condivisioni CIFS e SCVMM

Quando si crea un volume da utilizzare per le condivisioni CIFS e System Center Virtual Machine Manager (SCVMM), il volume deve essere di tipo NTFS. Per creare il volume con NTFS, immettere quanto segue: `_vol create -vserver <vserver_name> -volume <volume_name> -aggregate <aggr_name> -size<volume_size> -security-style ntfs_`
