---
settings:
  name: NetApp SMI-S Provider
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: it-it,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: Documenti del provider SMI-S di NetApp
    url: "/index.html"
  - title: Note di rilascio
    url: "/releasenotes.html"
  - title: Panoramica di NetApp SMI-S Provider
    entries:
    - title: Panoramica
      url: "/concept-overview.html"
    - title: Novità di questa release
      url: "/reference-new-in-this-release-smis.html"
    - title: Utilizzi del provider SMI-S di NetApp
      url: "/reference-uses-of-data-ontap-smi-s-agent.html"
    - title: Dimensionamento e performance del provider SMI-S di NetApp
      url: "/reference-smi-s-agent-sizing-and-performance-information.html"
    - title: Componenti del provider SMI-S di NetApp
      url: "/reference-data-ontap-smi-s-agent-components.html"
    - title: Protocolli NetApp SMI-S Provider
      url: "/reference-data-ontap-smi-s-agent-protocols.html"
    - title: In che modo NetApp SMI-S Provider interagisce con un host
      url: "/concept-how-smi-s-provider-interacts-with-a-host.html"
    - title: Profili SMI-S.
      url: "/concept-smi-s-profiles.html"
  - title: Workflow di implementazione
    url: "/concept-deployment-workflow.html"
  - title: Prepararsi per l'implementazione
    entries:
    - title: Panoramica
      url: "/concept-prepare-for-deployment-overview.html"
    - title: Versioni dei sistemi operativi supportate
      url: "/reference-supported-operating-systems.html"
    - title: Requisiti hardware
      url: "/reference-hardware-requirements.html"
    - title: Licenze richieste
      url: "/reference-required-licenses.html"
    - title: Piattaforme cluster supportate
      url: "/reference-supported-platforms.html"
    - title: Scarica il pacchetto software NetApp SMI-S Provider
      url: "/task-download-smi-s-provider.html"
  - title: Installare NetApp SMI-S Provider
    entries:
    - title: Installare NetApp SMI-S Provider su un host Windows
      url: "/task-install-smi-s-agent-on-a-windows-host.html"
  - title: Disinstallare NetApp SMI-S Provider
    entries:
    - title: Disinstallare NetApp SMI-S Provider da un host Windows
      url: "/task-uninstall-smi-s-agent-from-a-windows-host.html"
  - title: Convalida della preconfigurazione
    entries:
    - title: Panoramica
      url: "/concept-preconfiguration-task-overview.html"
    - title: Verificare lo stato del server CIM
      url: "/task-verify-the-cim-server-status.html"
    - title: Aggiungere un utente del server CIM
      url: "/task-add-cim-server-users.html"
    - title: Verificare che il sistema storage funzioni correttamente
      url: "/task-verify-that-the-storage-system-is-working-correctly.html"
    - title: Generare un certificato autofirmato per il server CIM
      url: "/task-generate-a-self-signed-certificate-for-the-cim-server-windows.html"
  - title: Gestire il server CIM
    url: "/task-manage-the-cim-server.html"
  - title: Gestire i sistemi storage
    url: "/task-manage-storage-systems.html"
  - title: Gestire gli utenti del server CIM
    entries:
    - title: Panoramica
      url: "/task-manage-cim-server-users-overview.html"
    - title: Tipi di utenti CIM e operazioni associate
      url: "/reference-types-of-cim-users-and-associated-operations.html"
  - title: Gestire le impostazioni di configurazione di CIMOM
    url: "/task-manage-cimom-configuration-settings.html"
  - title: Gestire logging e traccia
    entries:
    - title: Panoramica
      url: "/concept-manage-logging-and-tracing-overview.html"
    - title: Configurare le impostazioni del registro
      url: "/task-configure-log-settings.html"
      entries:
      - title: Livelli di registrazione
        url: "/reference-logging-levels.html"
    - title: Gestire il tracciamento
      url: "/concept-manage-tracing.html"
      entries:
      - title: Specificare le impostazioni di traccia
        url: "/task-specify-trace-settings.html"
        entries:
        - title: Valori di impostazione della traccia
          url: "/reference-trace-setting-values.html"
      - title: Specificare la dimensione del file di traccia
        url: "/task-specify-trace-file-size.html"
      - title: Specificare il numero di file di traccia salvati
        url: "/task-specify-the-number-of-trace-files-saved.html"
    - title: Attiva o disattiva il registro di controllo per i comandi SMI-S.
      url: "/task-enable-or-disable-audit-log-for-smi-s-commands.html"
  - title: Gestire le impostazioni avanzate del provider SMI-S.
    entries:
    - title: Panoramica
      url: "/concept-manage-smi-s-agent-advanced-settings-overview.html"
    - title: Specificare l'intervallo di aggiornamento automatico della cache del
        provider SMI-S.
      url: "/task-specify-the-smi-s-agent-cache-refresh-interval.html"
    - title: Specificare il valore concreto della durata del lavoro
      url: "/task-specify-the-concrete-job-lifetime-value.html"
    - title: Specificare il valore di timeout di ONTAPI
      url: "/task-specify-the-ontapi-timeout-value.html"
    - title: Specificare il numero massimo di thread per coda del servizio messaggi
      url: "/task-specify-the-maximum-number-of-threads-per-message-service-queue.html"
    - title: Attiva o disattiva l'autenticazione per il provider SMI-S di NetApp
      url: "/task-enable-or-disable-authentication-for-smi-s-provider.html"
    - title: Abilitare le indicazioni nel provider SMI-S.
      url: "/task-enable-indications-in-smi-s-agent.html"
  - title: Gestire SLP
    entries:
    - title: Panoramica
      url: "/concept-manage-slp-overview.html"
    - title: Specificare le opzioni di configurazione SLP
      url: "/concept-specify-slp-configuration-options.html"
      entries:
      - title: gestione dei file slp.conf
        url: "/reference-editing-the-slp-conf-file.html"
  - title: Comandi CIMOM
    entries:
    - title: cimconfig
      url: "/reference-cimconfig-command-options.html"
  - title: Comandi utente CIM
    entries:
    - title: cimuser
      url: "/reference-cimuser-command-options.html"
  - title: Comandi del provider SMI-S.
    entries:
    - title: Panoramica
      url: "/concept-smi-s-provider-commands-overview.html"
    - title: aggiunta di smi
      url: "/reference-smis-add.html"
    - title: smi addsicuro
      url: "/reference-smis-addsecure.html"
    - title: cimom. smi
      url: "/reference-smis-cimom.html"
    - title: cimserver smi
      url: "/reference-smis-cimserver.html"
    - title: classe smi
      url: "/reference-smis-class.html"
    - title: visualizzazione della configurazione smi
      url: "/reference-smis-config-show.html"
    - title: crp. smi
      url: "/reference-smis-crp.html"
    - title: smi crsp
      url: "/reference-smis-crsp.html"
    - title: eliminazione smi
      url: "/reference-smis-delete.html"
    - title: dischi smi
      url: "/reference-smis-disks.html"
    - title: esportazioni di smi
      url: "/reference-smis-exports.html"
    - title: iniziatori smi
      url: "/reference-smis-initiators.html"
    - title: smi concessi in licenza
      url: "/reference-smis-licensed.html"
    - title: elenco smi
      url: "/reference-smis-list.html"
    - title: lun smi
      url: "/reference-smis-luns.html"
    - title: spazi dei nomi smi
      url: "/reference-smis-namespaces.html"
    - title: pool di smi
      url: "/reference-smis-pools.html"
    - title: aggiornamento delle smi
      url: "/reference-smis-refresh.html"
    - title: slpd. smi
      url: "/reference-smis-slpd.html"
    - title: versione smi
      url: "/reference-smis-version.html"
    - title: volumi smi
      url: "/reference-smis-volumes.html"
  - title: Comandi SLP
    entries:
    - title: slptool
      url: "/reference-slptool-command-options.html"
    - title: slptool findattrs
      url: "/reference-slptool-findattrs.html"
    - title: slptool findsrvs
      url: "/reference-slptool-findsrvs.html"
  - title: Risolvere i problemi del provider SMI-S.
    entries:
    - title: Panoramica
      url: "/concept-troubleshoot-smi-s-agent-overview.html"
    - title: Errore accesso negato
      url: "/reference-access-is-denied-error.html"
    - title: Possibili errori durante il caricamento delle librerie condivise
      url: "/reference-possible-errors-when-loading-shared-libraries.html"
    - title: Connessione rifiutata
      url: "/reference-connection-refused-error.html"
    - title: 'Ritorno filer: Nessun elemento ONTAP in risposta'
      url: "/reference-no-ontap-element-in-response-error.html"
    - title: Non sono consentite operazioni clone/Snapshot
      url: "/reference-clone-snapshot-operations-are-not-allowed.html"
    - title: Avvertenza 26130
      url: "/reference-warning-26130.html"
    - title: 'HostAgentAccessDenied (ID: 26263)'
      url: "/reference-hostagentaccessdenied-error-id-26263.html"
    - title: Impossibile connettersi a localhost:5988
      url: "/reference-cannot-connect-to-localhost-5988-error.html"
    - title: Impossibile connettersi a localhost:5989
      url: "/reference-cannot-connect-to-localhost-5989-error.html"
    - title: Il provider SMI-S si blocca in Windows
      url: "/reference-handling-smi-s-agent-crashes-in-windows.html"
    - title: Problema di immissione di password contenenti caratteri speciali
      url: "/reference-entering-passwords-containing-special-characters.html"
    - title: Tecnologia di clonazione utilizzata nel provider SMI-S.
      url: "/concept-clone-technology-used-in-smi-s-agent-4-0.html"
    - title: Confermare la visibilità degli oggetti importanti
      url: "/concept-confirm-visibility-of-important-objects.html"
    - title: Requisito per l'utilizzo di file eshare su Windows
      url: "/concept-requirement-for-using-fileshares-in-windows.html"
    - title: I firewall non predefiniti devono avere porte aggiunte manualmente come
        eccezioni
      url: "/reference-non-default-firewalls-must-have-ports-manually-added-as-exceptions.html"
    - title: Impossibile aggiungere un sistema storage utilizzando una porta HTTP
        o HTTPS non predefinita
      url: "/reference-cannot-add-a-storage-system-using-a-nondefault-http-or-https-port.html"
    - title: Nessuna risposta dal server
      url: "/reference-no-response-from-the-server.html"
    - title: Problemi con la libreria di runtime
      url: "/reference-runtime-library-issues.html"
    - title: Il provider SMI-S di NetApp impiega molto tempo per iniziare
      url: "/reference-smi-s-agent-takes-a-long-time-to-start.html"
    - title: Spazio gestito totale per una discrepanza di un pool di storage (volume)
      url: "/reference-total-managed-space-for-a-storage-pool-aggregate-discrepancy.html"
    - title: Percorso di rete non trovato
      url: "/reference-network-path-not-found-error-during-vm-deployment.html"
    - title: Risorse di sistema insufficienti per completare il servizio richiesto
      url: "/reference-vm-provisioning-in-scvmm-fails-with-insufficient-system-resources-error.html"
    - title: Dimensione della condivisione SMB che scende a 0 in SCVMM
      url: "/reference-smb-share-size-dropping-to-0-in-scvmm.html"
    - title: Impossibile individuare o comunicare con il provider SMI-S durante l'operazione
        di riscan di SCVMM
      url: "/reference-scvmm-rescan-operation-failed-to-locate-or-communicate-with-smi-s-provider.html"
  - title: Note legali
    url: "/reference-legal-notices.html"
