---
permalink: reference-supported-operating-systems.html 
sidebar: sidebar 
keywords: installing, smi-s provider, verify, windows, host, operating systems 
summary: 'Prima di installare il provider SMI-S, verificare che l"host Windows stia eseguendo un sistema operativo supportato.' 
---
= Versioni dei sistemi operativi supportate
:allow-uri-read: 
:icons: font
:imagesdir: ./media/
:pp: &#43;&#43;


[role="lead"]
Ti consigliamo di installare SMI-S Provider sulla sua macchina virtuale Windows (VM) dedicata. Questa VM può trovarsi sullo stesso dominio per consentire una gestione sicura e comoda.

Prima di installare il provider SMI-S, verificare che l'host Windows stia eseguendo un sistema operativo supportato.

[cols="3*"]
|===
| Sistema operativo | Versioni supportate | Software client richiesto 


 a| 
Windows
 a| 
* Microsoft Windows Server 2025
* Microsoft Windows Server 2022
* Microsoft Windows Server 2019
* Microsoft Windows Server 2016

 a| 
Le librerie runtime di Microsoft Visual C{pp} 2010 vengono installate automaticamente durante l'installazione di SMI-S Provider. Per evitare potenziali problemi relativi alle librerie di runtime, è necessario installare Microsoft Visual C{pp} 2010 Redistributable Package (x86) dal seguente percorso: http://www.microsoft.com[]

|===


== Assicurarsi che la macchina host del provider soddisfi le specifiche

Per eseguire SMI-S Provider, il computer host del provider deve soddisfare le seguenti specifiche:

* Il provider non può essere installato direttamente su un nodo Hyper-V. In alternativa, è possibile installarlo su una VM Hyper-V.
* System Center Virtual Machine Manager (SCVMM) non deve essere in esecuzione sulla macchina host del provider.
* Il computer host del provider non deve eseguire altri programmi che richiedono molta memoria.
* La macchina host del provider non deve eseguire provider SMI-S di altri fornitori.

