---
permalink: reference-cannot-connect-to-localhost-5988-error.html 
sidebar: sidebar 
keywords: troubleshooting, issue, encounter 
summary: Problemi riscontrati con NetApp SMI-S Provider. 
---
= Impossibile connettersi a localhost:5988
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


* *Messaggio*
+
`Cannot connect to localhost:5988. Connection failed. Trying to connect to localhost:5988`

* *Descrizione*
+
Questo messaggio viene visualizzato quando le connessioni HTTPS sono disattivate o la porta HTTPS non è impostata su 5988 o se il provider ha smesso di funzionare e rimane in uno stato di visualizzazione.

* *Azione correttiva*
+
Verificare che i valori di `enableHttpsConnection` e. `httpsPort` sono corretti:

+
`cimconfig -g enableHttpConnection`

+
`cimconfig -g enableHttpsConnection`

+
`cimconfig -g httpPort`

+
`cimconfig -g httpsPort`

+
Se `enableHttpConnection` oppure `enableHttpsConnection` non è impostato su `true`, immettere i seguenti comandi:

+
`cimconfig -s enableHttpConnection -p`

+
`smis cimserver restart`

+
Se `httpPort` non è impostato su 5988, immettere i seguenti comandi:

+
`cimconfig -s httpPort=5988 -p`

+
`smis cimserver restart`

+
Se il provider ha smesso di funzionare e rimane in uno stato di sospensione, aprire Task Manager e terminare il processo, quindi riavviare il provider.


