---
permalink: reference-warning-26130.html 
sidebar: sidebar 
keywords: troubleshooting, issue, encounter 
summary: Problemi riscontrati con NetApp SMI-S Provider. 
---
= Avvertenza 26130
:allow-uri-read: 
:icons: font
:imagesdir: ./media/




== Messaggio

`Warning (26130) Storage pool has been allocated to host group where none of hosts in host group has access to storage array.`



== Descrizione

Questo errore si verifica quando si assegna la capacità di storage e si concede l'accesso a un array agli host che si trovano in un gruppo di host. Con questo avviso, è impossibile inserire le macchine virtuali nei sistemi storage.



== Azione correttiva

. Su ciascun computer host, aggiungere l'indirizzo IP di ciascun sistema di storage all'applicazione iSCSI Initiator.
. Se necessario, su ciascun sistema storage, per ogni computer host, creare un igroup univoco collegato al nome del nodo iSCSI appropriato dal computer host corrispondente.
. Per ogni computer host connesso a ONTAP, aprire l'applicazione MPIO e aggiungere il seguente ID hardware:
+
** Per ONTAP, immettere `*NETAPP LUN C-Mode*`.


. Riavviare i computer host.
. Rimuovere il provider.
. Impostare nuovamente il pool di storage.

