---
permalink: reference-cannot-add-a-storage-system-using-a-nondefault-http-or-https-port.html 
sidebar: sidebar 
keywords: troubleshooting, issue, encounter 
summary: Problemi riscontrati con NetApp SMI-S Provider. 
---
= Impossibile aggiungere un sistema storage utilizzando una porta HTTP o HTTPS non predefinita
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


* *Problema*
+
Non è possibile aggiungere un sistema storage che esegue HTTP o HTTPS su una porta non predefinita.

* *Causa*
+
Per impostazione predefinita, il provider SMI-S di NetApp utilizza la porta 80 per la comunicazione con i sistemi storage su HTTP e la porta 443 per la comunicazione su HTTPS.

* *Azione correttiva*
+
Utilizzare il seguente comando per aggiungere un sistema di storage che utilizza una porta diversa da 80 per il traffico HTTP o la porta 443 per il traffico HTTPS:

+
`cimcli ci -n root/ontap ONTAP_FilerData hostName=_storage_sys_ip_address_ port=_non_default_port_ userName=_storage_sys_user_ password=_storage_sys_pwd_ comMechanism=HTTP -u _agent_user_ -p _agent_pwd_-llocalhost:5989 -s`

+
`-u`, `-p`, `-l`, e. `-s` sono parametri facoltativi.





== Aggiunta di un sistema storage che utilizza la porta 8000 per il traffico HTTP

`cimcli ci -n root/ontap ONTAP_FilerData hostName=10.60.167.12 port=8000 userName=root password=netapp1! comMechanism=HTTP -u root -p netapp1! -l localhost:5989 -s --timeout 180`
