---
permalink: reference-entering-passwords-containing-special-characters.html 
sidebar: sidebar 
keywords: troubleshooting, issue, encounter 
summary: Problemi riscontrati con NetApp SMI-S Provider. 
---
= Problema di immissione di password contenenti caratteri speciali
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


* *Problema*
+
Nei sistemi operativi in lingua inglese, utilizzando una password contenente caratteri speciali con `smis` Il comando non funziona in un ambiente Windows. Questo problema non è stato testato con sistemi operativi diversi dall'inglese.

* *Causa*
+
In Windows, i seguenti caratteri, più eventuali spazi, sono considerati caratteri speciali e causano un errore di immissione della password se la password non è racchiusa tra virgolette:

+
, & ' < > ; | = {caret} "

* *Azione correttiva*
+
Se una password contiene spazi o caratteri speciali, racchiuderla tra virgolette doppie (" ") quando viene utilizzata in `smis` comando. Si noti che il carattere della virgoletta (") è un carattere speciale e non deve mai essere utilizzato nella password.





== Immissione di password con caratteri speciali

`smis add 1.2.3.4 Administrator "pass word"`

`smis add 1.2.3.4 Administrator "pass&word"`
