---
permalink: task-verify-the-cim-server-status.html 
sidebar: sidebar 
keywords: install, netapp smi-s provider, verify, cim server, automatic, access 
summary: 'Dopo aver installato NetApp SMI-S Provider, è necessario verificare che il server CIM si sia avviato automaticamente dopo aver effettuato l"accesso al provider SMI-S.' 
---
= Verificare lo stato del server CIM
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Dopo aver installato NetApp SMI-S Provider, è necessario verificare che il server CIM si sia avviato automaticamente dopo aver effettuato l'accesso al provider SMI-S.

.Prima di iniziare
È necessario disporre delle credenziali di accesso come amministratore.

.Fasi
. Accedere come Amministratore.
. Accedere al provider SMI-S di NetApp accedendo alla directory in cui si trovano gli eseguibili:
+
[cols="2*"]
|===
| Se si utilizza... | Quindi... 


 a| 
Prompt dei comandi (con privilegi amministrativi elevati)
 a| 
Selezionare `C:\Program Files (x86)\NetApp\smis\pegasus\bin`



 a| 
Menu *Start* > *programmi*
 a| 
Fare clic con il pulsante destro del mouse su *NetApp SMI-S Provider* e selezionare `Run as Administrator`.

|===
. Visualizzare lo stato del server CIM:
+
`*smis cimserver status*`

+
Se il server CIM è stato avviato, viene visualizzato il seguente messaggio:

+
`NetApp SMI-S Provider is running.`


