---
permalink: task-generate-a-self-signed-certificate-for-the-cim-server-windows.html 
sidebar: sidebar 
keywords: ssl authentication, enable, cim server, installation, self-signed certificate 
summary: 'Per impostazione predefinita, l"autenticazione SSL è attivata per il server CIM. Durante l"installazione del provider SMI-S, nella directory pegasus viene installato un certificato autofirmato per il server CIM. È possibile generare un certificato autofirmato e utilizzarlo invece del certificato predefinito.' 
---
= Generare un certificato autofirmato per il server CIM
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Per impostazione predefinita, l'autenticazione SSL è attivata per il server CIM. Durante l'installazione del provider SMI-S, nel viene installato un certificato autofirmato per il server CIM `pegasus` directory. È possibile generare un certificato autofirmato e utilizzarlo invece del certificato predefinito.

.Prima di iniziare
* È necessario aver già effettuato l'accesso come amministratore.
* È necessario aver già effettuato l'accesso al provider SMI-S.


.Fasi
. Scaricare il `openssl.cnf` file dalla seguente posizione: link:http://web.mit.edu/crypto/openssl.cnf["http://web.mit.edu/crypto/openssl.cnf"^]
. Spostare il `openssl.cnf` file nella directory bin:
+
`*%PEGASUS_HOME%\bin\openssl.cnf*`

. Impostare `OPENSSL_CONF` variabile ambientale in base alla posizione di `openssl.cnf` file:
+
`*C:\ >set OPENSSL_CONF=%PEGASUS_HOME%\bin\openssl.cnf*`

+
In questo modo si imposta la variabile di ambiente solo per la durata della sessione corrente del prompt dei comandi. Se si desidera impostare in modo permanente la variabile di ambiente, è possibile utilizzare una delle seguenti opzioni:

+
** Accedere a *Proprietà > variabili ambientali* e aggiornare la variabile in *sistema*.
** Utilizzare il prompt dei comandi per impostare in modo permanente la variabile:
+
`*setx OPENSSL_CONF “%PEGASUS_HOME%\bin\openssl.cnf*`.

+
La variabile viene impostata quando si apre una nuova sessione del prompt dei comandi.



. Passare a. `%PEGASUS_HOME%\bin` directory:
+
`*C:\cd %pegasus_home%\bin*`

. Generare una chiave privata:
+
`*openssl genrsa -out cimom.key 2048*`

. Generare una richiesta di certificato:
+
`*openssl req -new -key cimom.key -out cimom.csr*`

. Quando richiesto, immettere le informazioni per la richiesta di certificato.
. Generare il certificato autofirmato:
+
`*openssl x509 -in cimom.csr -out cimom.cert -req -signkey cimom.key -days 1095*`

+
È possibile specificare un numero diverso di giorni per i quali il certificato è valido.

. Copiare il `cimom.key` e. `cimom.cert` file in `pegasus` Directory (Windows: `C:\Program Files (x86)\NetApp\smis\pegasus`).




== Risultato

L'intervallo di date del certificato inizia alla data corrente e viene eseguito per il numero di giorni specificato.
