---
permalink: task-enable-or-disable-authentication-for-smi-s-provider.html 
sidebar: sidebar 
keywords: smi-s provider, authentication, enable, errors, system, disable 
summary: 'Per impostazione predefinita, l"autenticazione è attivata per il provider SMI-S. Se l"autenticazione causa errori nel sistema, è possibile disattivarlo. Se l"autenticazione è stata disattivata e si desidera riattivarla, è possibile farlo.' 
---
= Attiva o disattiva l'autenticazione per il provider SMI-S di NetApp
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Per impostazione predefinita, l'autenticazione è attivata per il provider SMI-S. Se l'autenticazione causa errori nel sistema, è possibile disattivarlo. Se l'autenticazione è stata disattivata e si desidera riattivarla, è possibile farlo.

.Prima di iniziare
* È necessario disporre delle credenziali di accesso come amministratore.
* È necessario aver già effettuato l'accesso come amministratore.
* Qualsiasi client, incluso System Center Virtual Machine Manager (SCVMM), deve essere connesso al provider utilizzando cimuser e cimpassword.


.Fasi
. Accedi al provider SMI-S di NetApp.
. Impostare l'autenticazione per il provider SMI-S:
+
[cols="2*"]
|===
| Azione | Comando 


 a| 
*Attivare l'autenticazione se precedentemente disattivata*
 a| 
`*cimconfig -p -s enableAuthentication=true*`



 a| 
*Disattiva autenticazione*
 a| 
`*cimconfig -p -s enableAuthentication=false*`

|===
+
CIMOM non utilizza l'autenticazione di Windows.

. Riavviare NetApp SMI-S Provider:
+
`*smis cimserver restart*`


